### PR TITLE
Build with gh actions

### PR DESCRIPTION
**Pull request by khwilson**
This series of commits:

* Builds with Ruby 3.0.3 (to match @grantmcdermott 's local environment)
* Uses jekyll 4 (for the same reason)
* Builds with github actions instead of github pages to pick up the stata lexer and other goodies

Do note! The name of the folder with the GA yaml file is _not_ `workflows` because I'm not an owner of the repo. You'll need to change the name of the folder

### CODE REVIEW

**Comment by grantmcdermott** [comment]
(fyi just made you co-owner admin/owner in case you want to change the yaml name)

**Review by grantmcdermott — APPROVED** [review]
Thanks @khwilson! I'll just change the `workflows/` dir name on the backend after merging this PR.

As an aside, I've just peeked at the rouge repo and it looks like @reifjulian's Stata lexer PR is finally getting traction in time for the next release. https://github.com/rouge-ruby/rouge/pull/1658

I think I'll stick with this GH Actions workflow for the moment. But it's something to keep an eye on in case I (we?) decide to revert back to the normal GH Pages build later. (Same for LOST, notwithstanding the extra goodies and code checking you've implemented though actions.)

**Comment by khwilson** [comment]
Oh nice! In general, I think that if you don’t mind the overhead, the flexibility of a CI system is worth the headache. But will be very happy to have a built in rouge lexer and so we can just use that instead!

**Comment by reifjulian** [comment]
Yes, the Stata lexer finally got pushed to the master branch :) It won't be available on automatic GH Pages builds until (1) Rouge releases a new version; and then (2) [GH Pages](https://pages.github.com/versions/) updates to the newest version of Rouge. That could take anywhere from a few weeks to over a year. I'll try to put in a request to GH once the next Rouge release is out. 

In the meantime, you can always access the Stata lexer by adding the following line to your gemfile:
```ruby
gem "rouge", git: 'https://github.com/reifjulian/rouge', branch: 'stata'
```

I tried just now to instead have the gemfile reference the master branch of `rouge-ruby`, but that caused a bundle conflict with `github-pages` that I couldn't figure out how to resolve. So I'm leaving my branch undeleted for now.

**Pull request merged**
