### PR TITLE
Fix box sizing for code and allow local builds

### PR DESCRIPTION
**Pull request by khwilson**
### Build changes
In order to build locally, you have to add some settings that allows jekyll to understand what's going on. (GitHub, understandably, waves a lot of this away). With these changes, you can now `bundle exec jekyll serve` locally so you don't have to do a bunch of back and forth with the GitHub CI system.

* Add a Gemfile to allow for local builds
* Edit _config.yml to pick up those gems

### Layout changes
  * Remove the `layout: default` from `index.md`. It doesn't exist when using the raw just-the-docs plugin

### CSS changes
  * Change `.flex-container`'s `width` setting to a `max-width` setting to match that of the `.main` of just-the-docs
  * Copy the `.main` CSS from just-the-docs to custom.scss to get a correct build order

### CODE REVIEW

**Review by grantmcdermott — APPROVED** [review]

**Comment by grantmcdermott** [comment]
Thanks @khwilson, looks great.

I was having a hard time building locally because of ruby 3.0 (local) vs 2.7 (GH pages) issue. But everything seems to be working after toggled around with that and added "webrick" to the gemfile. Hopefully that doesn't break GH pages CI build... Do you have any thoughts on this before I merge?

**Comment by khwilson** [comment]
Oh yeah I’d highly recommend rvm. I build with 2.6 on lost stats for this reason.

**Comment by khwilson** [comment]
And you should definitely commit the lock file. This file reifies all the dependencies up and down the chain into actual versions. This way you’re (mostly) guaranteed to get consistent builds. If somebody makes an update upstream you’re not subject to it automatically.

Typically with ruby you also add a .ruby-version file which allows you to specify the ruby version you’re building on.

Absent going full docker, this is about the best you can get for consistent builds.

**Comment by grantmcdermott** [comment]
Sorry, finally taking a look at this again after beginning of term madness. Do you know why the actions deployment is [failing](https://github.com/docstest/doctest.github.io/deployments/activity_log?environment=github-pages)?

**Comment by khwilson** [comment]
Ah yeah. So it's failing because it can't find the `just-the-docs` gem. This is one of the weird issues that distinguishing local and Github builds. Let me take a look this afternoon!

**Comment by grantmcdermott** [comment]
Thanks mate. If you want to just shim in the CI scaffolding you used for LOST that's totally fine with me (automatic code testing aside, probably). It would be great to get your Stata rouge lexer anyway so we can have nicely formatted code there too.

**Comment by khwilson** [comment]
OK, so upon doing some research, here's what I determined:

* GitHub pages now builds explicitly with the [`github-pages` gem](https://github.com/github/pages-gem) with the command `bundle exec github-pages build`
* This gem fixes the [versions](https://pages.github.com/versions/) of many plugins, including jekyll at 3.9.0.
* It does _not_ seem to allow non-whitelisted plugins, so to get the stata lexer you'd need to
  - Get Rouge to accept a PR for the new lexer, and
  - Get GitHub to upgrade the version of Rouge in the `github-pages` gem, which seems a tall order

So to allow for the stata lexer, you definitely need to build everything yourself with actions. I (will) have made 2 PRs (by the time you read this):
* #2 reverts the `_config.yml` to use the remote `just-the-docs` theme and will build with the `github-pages` gem. However, it cannot have the stata lexer for the above reasons;
* #3 imports the CI pipeline (minus code checks for now, though that's easy enough to add in) from LOST stats

You can choose which one you want :-)

**Comment by grantmcdermott** [comment]
@khwilson you're the man!

Thanks bud. I'm tagging out of childcare duties shortly so will take a proper look then.

**Pull request merged**
